apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: travelnote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: minwoooo3396/travelnote-frontend:build-8 # 방금 Push한 이미지
        ports:
        - containerPort: 80