apiVersion: apps/v1
kind: Deployment
metadata:
  name: member-service
  namespace: travelnote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: member-service
  template:
    metadata:
      labels:
        app: member-service
    spec:
      containers:
      - name: member-service
        image: minwoooo3396/travelnote-member:v1 # ✅ Docker Hub 이미지로 변경
        ports:
        - containerPort: 8081
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: secret-key